swagger:
  swagger: "2.0"
  info:
    description: "API documentation for the Food Ordering Application"
    version: "1.0.0"
    title: "Food Ordering API"
  host: "localhost:8080"
  basePath: "/api"
  schemes:
    - "http"
  paths:
    /users:
      get:
        summary: "Get all users"
        responses:
          200:
            description: "Successful operation"
      post:
        summary: "Create a new user"
        parameters:
          - name: "user"
            in: "body"
            required: true
            schema:
              $ref: "#/definitions/User"
        responses:
          201:
            description: "User created"
    /restaurants:
      get:
        summary: "Get all restaurants"
        responses:
          200:
            description: "Successful operation"
      post:
        summary: "Create a new restaurant"
        parameters:
          - name: "restaurant"
            in: "body"
            required: true
            schema:
              $ref: "#/definitions/Restaurant"
        responses:
          201:
            description: "Restaurant created"
    /menu-items:
      get:
        summary: "Get all menu items"
        responses:
          200:
            description: "Successful operation"
      post:
        summary: "Create a new menu item"
        parameters:
          - name: "menuItem"
            in: "body"
            required: true
            schema:
              $ref: "#/definitions/MenuItem"
        responses:
          201:
            description: "Menu item created"
    /orders:
      get:
        summary: "Get all orders"
        responses:
          200:
            description: "Successful operation"
      post:
        summary: "Create a new order"
        parameters:
          - name: "order"
            in: "body"
            required: true
            schema:
              $ref: "#/definitions/Order"
        responses:
          201:
            description: "Order created"
    /payments:
      post:
        summary: "Process a payment"
        parameters:
          - name: "payment"
            in: "body"
            required: true
            schema:
              $ref: "#/definitions/Payment"
        responses:
          201:
            description: "Payment processed"
    /delivery:
      get:
        summary: "Get delivery status"
        responses:
          200:
            description: "Successful operation"
      post:
        summary: "Update delivery status"
        parameters:
          - name: "delivery"
            in: "body"
            required: true
            schema:
              $ref: "#/definitions/Delivery"
        responses:
          200:
            description: "Delivery status updated"
  definitions:
    User:
      type: "object"
      properties:
        user_id:
          type: "integer"
        name:
          type: "string"
        email:
          type: "string"
        password:
          type: "string"
        address:
          type: "string"
        phone:
          type: "string"
    Restaurant:
      type: "object"
      properties:
        restaurant_id:
          type: "integer"
        name:
          type: "string"
        address:
          type: "string"
        phone:
          type: "string"
        rating:
          type: "number"
          format: "float"
    MenuItem:
      type: "object"
      properties:
        item_id:
          type: "integer"
        restaurant_id:
          type: "integer"
        name:
          type: "string"
        description:
          type: "string"
        price:
          type: "number"
          format: "float"
        is_available:
          type: "boolean"
    Order:
      type: "object"
      properties:
        order_id:
          type: "integer"
        user_id:
          type: "integer"
        restaurant_id:
          type: "integer"
        order_time:
          type: "string"
          format: "date-time"
        status:
          type: "string"
        total_price:
          type: "number"
          format: "float"
    Payment:
      type: "object"
      properties:
        payment_id:
          type: "integer"
        order_id:
          type: "integer"
        payment_method:
          type: "string"
        amount:
          type: "number"
          format: "float"
        payment_time:
          type: "string"
          format: "date-time"
        status:
          type: "string"
    Delivery:
      type: "object"
      properties:
        delivery_id:
          type: "integer"
        order_id:
          type: "integer"
        delivery_address:
          type: "string"
        delivery_time:
          type: "string"
          format: "date-time"
        delivery_status:
          type: "string"
        delivery_person:
          type: "string"